# Generated by Django 5.0.6 on 2024-06-17 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=500)),
                ('instructions', models.CharField(max_length=10000)),
                ('ingredients', models.CharField(max_length=10000)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('dessert', 'Dessert')], default='breakfast', max_length=50)),
                ('cuisine_types', models.CharField(choices=[('italian', 'Italian'), ('african', 'African'), ('american', 'American'), ('caribbean', 'Caribbean'), ('asian', 'Asian'), ('middle_eastern', 'Middle Eastern'), ('chinese', 'Chinese'), ('indian', 'Indian'), ('pakistani', 'Pakistani'), ('indonesian', 'Indonesian'), ('european', 'European'), ('oceanic', 'Oceanic')], default='italian', max_length=50)),
                ('calories', models.IntegerField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
    ]
