# Generated by Django 5.0.6 on 2024-06-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="calories",
        ),
    ]
