# Generated by Django 5.0.6 on 2024-06-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0002_remove_recipe_calories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recipe",
            old_name="author",
            new_name="user",
        ),
    ]
