# Generated by Django 5.0.6 on 2024-06-19 12:46

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes_app", "0003_rename_author_recipe_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=djrichtextfield.models.RichTextField(max_length=10000),
        ),
    ]
